name: Release Charts

on: push

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "Shubham Tatvamasi"
          git config user.email "shubhamtatvamasi@gmail.com"

      - name: Install Helm
        uses: azure/setup-helm@v3

      - name: Add helm repo
        run: helm repo add orc8r https://shubhamtatvamasi.github.io/magma-charts-04-09-2023

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.5.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
